# Generated by Django 4.0.3 on 2022-03-29 12:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_uuid', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('reading_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_uuid', models.UUIDField(default=uuid.uuid4)),
                ('value', models.DecimalField(decimal_places=1, max_digits=2)),
                ('unit', models.TextField()),
                ('recorded_at', models.DateTimeField()),
            ],
        ),
    ]
