version: '3.9'

services:

  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./backend/app:/app

  postgres:
    container_name: postgres
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
